/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.lsuc.lsuc.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class ChangeRequestTrendGraphResponse implements Serializable {

    @ColumnAlias("CALCULATED_DATE")
    private String calculatedDate;
    @ColumnAlias("DATE_COUNT")
    private Integer dateCount;
    @ColumnAlias("TYPE")
    private Integer type;

    public String getCalculatedDate() {
        return this.calculatedDate;
    }

    public void setCalculatedDate(String calculatedDate) {
        this.calculatedDate = calculatedDate;
    }

    public Integer getDateCount() {
        return this.dateCount;
    }

    public void setDateCount(Integer dateCount) {
        this.dateCount = dateCount;
    }

    public Integer getType() {
        return this.type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ChangeRequestTrendGraphResponse)) return false;
        final ChangeRequestTrendGraphResponse changeRequestTrendGraphResponse = (ChangeRequestTrendGraphResponse) o;
        return Objects.equals(getCalculatedDate(), changeRequestTrendGraphResponse.getCalculatedDate()) &&
                Objects.equals(getDateCount(), changeRequestTrendGraphResponse.getDateCount()) &&
                Objects.equals(getType(), changeRequestTrendGraphResponse.getType());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCalculatedDate(),
                getDateCount(),
                getType());
    }
}
