/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.lsuc.lsuc.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.math.BigInteger;
import java.util.Date;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetStatusChangeDetailsResponse implements Serializable {

    @ColumnAlias("LicenseeClass")
    private String licenseeClass;
    @ColumnAlias("EffectiveDate")
    private Date effectiveDate;
    @ColumnAlias("EffectiveTo")
    private Date effectiveTo;
    @ColumnAlias("PracticeGroup")
    private String practiceGroup;
    @ColumnAlias("isPrimary")
    private String isPrimary;
    @ColumnAlias("revtstmp")
    private BigInteger revtstmp;
    @ColumnAlias("changedBy")
    private String changedBy;

    public String getLicenseeClass() {
        return this.licenseeClass;
    }

    public void setLicenseeClass(String licenseeClass) {
        this.licenseeClass = licenseeClass;
    }

    public Date getEffectiveDate() {
        return this.effectiveDate;
    }

    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }

    public Date getEffectiveTo() {
        return this.effectiveTo;
    }

    public void setEffectiveTo(Date effectiveTo) {
        this.effectiveTo = effectiveTo;
    }

    public String getPracticeGroup() {
        return this.practiceGroup;
    }

    public void setPracticeGroup(String practiceGroup) {
        this.practiceGroup = practiceGroup;
    }

    public String getIsPrimary() {
        return this.isPrimary;
    }

    public void setIsPrimary(String isPrimary) {
        this.isPrimary = isPrimary;
    }

    public BigInteger getRevtstmp() {
        return this.revtstmp;
    }

    public void setRevtstmp(BigInteger revtstmp) {
        this.revtstmp = revtstmp;
    }

    public String getChangedBy() {
        return this.changedBy;
    }

    public void setChangedBy(String changedBy) {
        this.changedBy = changedBy;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetStatusChangeDetailsResponse)) return false;
        final GetStatusChangeDetailsResponse getStatusChangeDetailsResponse = (GetStatusChangeDetailsResponse) o;
        return Objects.equals(getLicenseeClass(), getStatusChangeDetailsResponse.getLicenseeClass()) &&
                Objects.equals(getEffectiveDate(), getStatusChangeDetailsResponse.getEffectiveDate()) &&
                Objects.equals(getEffectiveTo(), getStatusChangeDetailsResponse.getEffectiveTo()) &&
                Objects.equals(getPracticeGroup(), getStatusChangeDetailsResponse.getPracticeGroup()) &&
                Objects.equals(getIsPrimary(), getStatusChangeDetailsResponse.getIsPrimary()) &&
                Objects.equals(getRevtstmp(), getStatusChangeDetailsResponse.getRevtstmp()) &&
                Objects.equals(getChangedBy(), getStatusChangeDetailsResponse.getChangedBy());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getLicenseeClass(),
                getEffectiveDate(),
                getEffectiveTo(),
                getPracticeGroup(),
                getIsPrimary(),
                getRevtstmp(),
                getChangedBy());
    }
}
