/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.lsuc.lsuc.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.math.BigInteger;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.lsuc.lsuc.VwLicenseeFilter;


/**
 * ServiceImpl object for domain model class VwLicenseeFilter.
 *
 * @see VwLicenseeFilter
 */
@Service("LSUC.VwLicenseeFilterService")
public class VwLicenseeFilterServiceImpl implements VwLicenseeFilterService {

    private static final Logger LOGGER = LoggerFactory.getLogger(VwLicenseeFilterServiceImpl.class);


    @Autowired
    @Qualifier("LSUC.VwLicenseeFilterDao")
    private WMGenericDao<VwLicenseeFilter, BigInteger> wmGenericDao;

    public void setWMGenericDao(WMGenericDao<VwLicenseeFilter, BigInteger> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "LSUCTransactionManager")
    @Override
	public VwLicenseeFilter create(VwLicenseeFilter vwLicenseeFilter) {
        LOGGER.debug("Creating a new VwLicenseeFilter with information: {}", vwLicenseeFilter);
        VwLicenseeFilter vwLicenseeFilterCreated = this.wmGenericDao.create(vwLicenseeFilter);
        return vwLicenseeFilterCreated;
    }

	@Transactional(readOnly = true, value = "LSUCTransactionManager")
	@Override
	public VwLicenseeFilter getById(BigInteger vwlicenseefilterId) throws EntityNotFoundException {
        LOGGER.debug("Finding VwLicenseeFilter by id: {}", vwlicenseefilterId);
        VwLicenseeFilter vwLicenseeFilter = this.wmGenericDao.findById(vwlicenseefilterId);
        if (vwLicenseeFilter == null){
            LOGGER.debug("No VwLicenseeFilter found with id: {}", vwlicenseefilterId);
            throw new EntityNotFoundException(String.valueOf(vwlicenseefilterId));
        }
        return vwLicenseeFilter;
    }

    @Transactional(readOnly = true, value = "LSUCTransactionManager")
	@Override
	public VwLicenseeFilter findById(BigInteger vwlicenseefilterId) {
        LOGGER.debug("Finding VwLicenseeFilter by id: {}", vwlicenseefilterId);
        return this.wmGenericDao.findById(vwlicenseefilterId);
    }


	@Transactional(rollbackFor = EntityNotFoundException.class, value = "LSUCTransactionManager")
	@Override
	public VwLicenseeFilter update(VwLicenseeFilter vwLicenseeFilter) throws EntityNotFoundException {
        LOGGER.debug("Updating VwLicenseeFilter with information: {}", vwLicenseeFilter);
        this.wmGenericDao.update(vwLicenseeFilter);

        BigInteger vwlicenseefilterId = vwLicenseeFilter.getRowNum();

        return this.wmGenericDao.findById(vwlicenseefilterId);
    }

    @Transactional(value = "LSUCTransactionManager")
	@Override
	public VwLicenseeFilter delete(BigInteger vwlicenseefilterId) throws EntityNotFoundException {
        LOGGER.debug("Deleting VwLicenseeFilter with id: {}", vwlicenseefilterId);
        VwLicenseeFilter deleted = this.wmGenericDao.findById(vwlicenseefilterId);
        if (deleted == null) {
            LOGGER.debug("No VwLicenseeFilter found with id: {}", vwlicenseefilterId);
            throw new EntityNotFoundException(String.valueOf(vwlicenseefilterId));
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

	@Transactional(readOnly = true, value = "LSUCTransactionManager")
	@Override
	public Page<VwLicenseeFilter> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all VwLicenseeFilters");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "LSUCTransactionManager")
    @Override
    public Page<VwLicenseeFilter> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all VwLicenseeFilters");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "LSUCTransactionManager")
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service LSUC for table VwLicenseeFilter to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

	@Transactional(readOnly = true, value = "LSUCTransactionManager")
	@Override
	public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "LSUCTransactionManager")
	@Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }



}

