/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.lsuc.lsuc.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.math.BigInteger;
import java.util.Map;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.runtime.file.model.Downloadable;

import com.lsuc.lsuc.VwLicenseeFilter;

/**
 * Service object for domain model class {@link VwLicenseeFilter}.
 */
public interface VwLicenseeFilterService {

    /**
     * Creates a new VwLicenseeFilter. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on VwLicenseeFilter if any.
     *
     * @param vwLicenseeFilter Details of the VwLicenseeFilter to be created; value cannot be null.
     * @return The newly created VwLicenseeFilter.
     */
	VwLicenseeFilter create(VwLicenseeFilter vwLicenseeFilter);


	/**
	 * Returns VwLicenseeFilter by given id if exists.
	 *
	 * @param vwlicenseefilterId The id of the VwLicenseeFilter to get; value cannot be null.
	 * @return VwLicenseeFilter associated with the given vwlicenseefilterId.
     * @throws EntityNotFoundException If no VwLicenseeFilter is found.
	 */
	VwLicenseeFilter getById(BigInteger vwlicenseefilterId) throws EntityNotFoundException;

    /**
	 * Find and return the VwLicenseeFilter by given id if exists, returns null otherwise.
	 *
	 * @param vwlicenseefilterId The id of the VwLicenseeFilter to get; value cannot be null.
	 * @return VwLicenseeFilter associated with the given vwlicenseefilterId.
	 */
	VwLicenseeFilter findById(BigInteger vwlicenseefilterId);


	/**
	 * Updates the details of an existing VwLicenseeFilter. It replaces all fields of the existing VwLicenseeFilter with the given vwLicenseeFilter.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on VwLicenseeFilter if any.
     *
	 * @param vwLicenseeFilter The details of the VwLicenseeFilter to be updated; value cannot be null.
	 * @return The updated VwLicenseeFilter.
	 * @throws EntityNotFoundException if no VwLicenseeFilter is found with given input.
	 */
	VwLicenseeFilter update(VwLicenseeFilter vwLicenseeFilter) throws EntityNotFoundException;

    /**
	 * Deletes an existing VwLicenseeFilter with the given id.
	 *
	 * @param vwlicenseefilterId The id of the VwLicenseeFilter to be deleted; value cannot be null.
	 * @return The deleted VwLicenseeFilter.
	 * @throws EntityNotFoundException if no VwLicenseeFilter found with the given id.
	 */
	VwLicenseeFilter delete(BigInteger vwlicenseefilterId) throws EntityNotFoundException;

	/**
	 * Find all VwLicenseeFilters matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching VwLicenseeFilters.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<VwLicenseeFilter> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all VwLicenseeFilters matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching VwLicenseeFilters.
     *
     * @see Pageable
     * @see Page
	 */
    Page<VwLicenseeFilter> findAll(String query, Pageable pageable);

    /**
	 * Exports all VwLicenseeFilters matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the VwLicenseeFilters in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the VwLicenseeFilter.
	 */
	long count(String query);

	/**
	 * Retrieve aggregated values with matching aggregation info.
     *
     * @param aggregationInfo info related to aggregations.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
	 * @return Paginated data with included fields.

     * @see AggregationInfo
     * @see Pageable
     * @see Page
	 */
	Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable);


}

